tasks.build = "cargo build --all --all-features"
tasks.build-release = "cargo build --all --all-features --release"
tasks.format = "cargo fmt -- --all"
tasks.lint = [
  "cargo clippy --all --all-features -- -D warnings",
  "cargo fmt --all -- --check",
]
tasks.release = "cargo release"

[tasks.test]
run = "cargo test --all --all-features -- --nocapture"
env = { RUST_LOG = "xx=trace" }

[tasks.coverage]
alias = "cov"
run = [
  "cargo llvm-cov --no-report --all --all-features -- --nocapture",
  "cargo llvm-cov report --lcov --output-path coverage.lcov",
  "cargo llvm-cov report",
]
env = { RUST_LOG = "xx=trace" }

[tasks.ci]
depends = ["build", "lint", "coverage"]

[env]
RUST_TEST_THREADS = '1'

[tools]
"cargo:cargo-llvm-cov" = "latest"
